### PR TITLE
Add pulse-counter to read fan RPM

### PR DESCRIPTION
**Pull request by TheDK**
If you'd like to include this let me know and I'll add some info to the readme as well...

### CODE REVIEW

**Review by patrickcollins12 — COMMENTED** [review]
Looks good! Would you mind adjusting the README as well to indicate how to wire it up? Note that I say "we won't use the tach pin" so you'd need to remove that as well.

**Comment by TheDK** [comment]
If have edited the readme to give info on the TACH pin --> See PR...

**Review by patrickcollins12 — APPROVED** [review]

**Review by patrickcollins12 — APPROVED** [review]

**Comment by patrickcollins12** [comment]
I've updated the Image to include the Tach Pin. Can you confirm no resistors are needed only the internal pullup?

**Comment by TheDK** [comment]
Yes, works fine for me.

**Comment by DunklesKaltesNichts** [comment]
If your board has internal pullups and you use them, then you don't need an external resistor as a pullup.

**Pull request merged**
